// User
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_USER_FAIL = 'LOGOUT_USER_FAIL';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
// Bookmarks
export const GET_BOOKMARKS = 'GET_BOOKMARKS';
export const GET_BOOKMARKS_FAIL = 'GET_BOOKMARKS_FAIL';
export const GET_BOOKMARKS_SUCCESS = 'GET_BOOKMARKS_SUCCESS';
export const GET_BOOKMARK = 'GET_BOOKMARK';
export const GET_BOOKMARK_FAIL = 'GET_BOOKMARK_FAIL';
export const GET_BOOKMARK_SUCCESS = 'GET_BOOKMARK_SUCCESS';
export const ADD_BOOKMARK = 'ADD_BOOKMARK';
export const ADD_BOOKMARK_FAIL = 'ADD_BOOKMARK_FAIL';
export const ADD_BOOKMARK_SUCCESS = 'ADD_BOOKMARK_SUCCESS';
export const DELETE_BOOKMARK = 'DELETE_BOOKMARK';
export const DELETE_BOOKMARK_FAIL = 'DELETE_BOOKMARK_FAIL';
export const DELETE_BOOKMARK_SUCCESS = 'DELETE_BOOKMARK_SUCCESS';
export const UPDATE_BOOKMARK = 'UPDATE_BOOKMARK';
export const UPDATE_BOOKMARK_FAIL = 'UPDATE_BOOKMARK_FAIL';
export const UPDATE_BOOKMARK_SUCCESS = 'UPDATE_BOOKMARK_SUCCESS';
